= drails_validator

image:https://travis-ci.org/drails-dart/drails_validator.svg?branch=master["Build Status", link="https://travis-ci.org/drails-dart/drails_validator"]

Library for validate models similar to JPA Bean validation. It provides a way to validate a dart object using constraints which we can use for validation. To check if the object is valid we need to invoke the function `validate` which returns an Object of type `ValidationResult` which contains a map of errors for every attribute of the object, for example:

* Create a new dart project

* Add dependencies to `pubspec.yaml`

```yaml
...
dependencies:
  ...
  drails_validator: ^0.1.0 #change it for the latest version
  ...

dev_dependencies:
  ...
include::example/pubspec.yaml[tag=build-runner]
  ...
```

* Create/edit the file `main.dart` in the folder `bin` and put next code on it:

```dart
include::example/bin/main.dart[tag=!*]
```

* run `pub run build_runner build`. Then you will see that the file `bin/drails_validator_sample.g.dart`
has been generated and it will contains the next code:

```dart
include::example/bin/main.g.dart[]
```

* Finally you can run the file `bin/drails_validator_sample.dart`. If everything is ok you will see next
output in console:

```
invalidPerson: isValid: false, errors: {firstName: [Length should be greather than 2], lastName: [Length should be greather than 2], email: [The entered email is invalid], dateOfBirth: [Values after now are not allowed], ssn: [The entered SSN is invalid]}
validPerson: isValid: true, errors: {}
```

== Add Localization

* install `l10n` package by running:

```
pub global activate l10n
```

* generate translations by running:

```
mkl10n -l es . <path-to-drails_validator-package>
```

WARNING: Remember to replace `<path-to-drails_validator-package>` by the correct path

* translate `intl_es.arb` file using link:https://translate.google.com/toolkit[Google Translate Toolkit]

* run again:

```
mkl10n -l es . <path-to-drails_validator-package>
```

* import the generated `messages_all.dart` file in the `main.dart` file:

```dart
include::example/bin/main.dart[tag=import-messages]
```

then set the default locale and initialize the messages by adding next code to main function:

```dart
main() {
...
include::example/bin/main.dart[tag=set-locale]
...
}
```

final code in `main.dart`:

```dart
include::example/bin/main.dart[tag=**]
```

== Edit the README file

Please don't edit the `README.md` file since this one is generated by `asciidoctor` and `pandoc`. Instead edit `_README.adoc` and then run:

```
asciidoctor _README.adoc -b docbokk
```

and then:

```
pandoc -f docbook -t gfm -o README.md _README.adoc
```