name: drails_validator
version: 0.0.2
author: Luis Vargas <luisvargastijerino@gmail.com>
description: A library useful for applications or for sharing on pub.dartlang.org.
homepage: https://github.com/luisvt/drails_validator
enviroment:
  sdk: ">=1.8.0 <2.0.0"
dependencies:
  validator: '>=0.0.7 <0.0.9'
  drails_commons: ^0.0.6
#  drails_commons:
#    path: ../drails_commons
  reflectable: '>=0.3.2 <0.4.0'
#  reflectable:
#    path: ../reflectable/reflectable
dev_dependencies:
  test: any
