name: drails_validator
version: 1.0.0+1
author: Luis Vargas <luisvargastijerino@gmail.com>
description: Library for validate models similar to JPA Bean validation.
homepage: https://github.com/luisvt/drails_validator
environment:
  sdk: ">=2.0.0 <3.0.0"
dependencies:
  validators: ^1.0.0
  dson: ^0.15.0
#  built_mirrors:
#    path: ../built_mirrors
#dependency_overrides:
#  built_mirrors:
#    path: ../built_mirrors
dev_dependencies:
  test: ^1.3.3
  build_runner: any
  build_test: any
