name: drails_validator
version: 0.1.0
author: Luis Vargas <luisvargastijerino@gmail.com>
description: Library for validate models similar to JPA Bean validation.
homepage: https://github.com/luisvt/drails_validator
environment:
  sdk: ">=1.8.0 <2.0.0"
dependencies:
  validator: '>=0.0.7 <0.0.9'
  dson: ^0.6.0
#  built_mirrors:
#    path: ../built_mirrors
#dependency_overrides:
#  built_mirrors:
#    path: ../built_mirrors
dev_dependencies:
  test: any
